test: isolate more tests that call subprocesses
The base `make test-Pkg` invocation sets JULIA_DEPOT_PATH to the builtin
DEPOT_PATH. However, Pkg tests assume that this DEPOT_PATH do not have any
registries. There were various places where we were accidentally using
this DEPOT_PATH and installing a registry there. Work around this by
unsetting it, isolating some subprocesses and adding a check on CI that
fails if any pre-set JULIA_DEPOT_PATH gets modified.

Ref https://github.com/JuliaLang/julia/issues/60058

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -77,6 +77,15 @@ jobs:
         env:
           JULIA_PKG_SERVER: ${{ matrix.pkg-server }}
           JULIA_TEST_VERBOSE_LOGS_DIR: ${{ github.workspace }}
+          JULIA_DEPOT_PATH: ${{ github.workspace }}/do_not_modify_depot
+      - name: Check that we did not modify JULIA_DEPOT_PATH
+        run: |
+          if [ -d "${{ github.workspace }}/do_not_modify_depot/registries" ]; then
+            echo "Error: Tests modified the JULIA_DEPOT_PATH"
+            exit 1
+          fi
+        env:
+          JULIA_DEPOT_PATH: ${{ github.workspace }}/do_not_modify_depot
       - uses: actions/upload-artifact@v5
         if: ${{ always() }}
         with:
